//
//  Cell.h
//  Spin Wave Genie
//
//  Created by Hahn, Steven E. on 2/6/13.
//  Copyright (c) 2013 Oak Ridge National Laboratory. All rights reserved.
//

#ifndef __Neighbors_H__
#define __Neighbors_H__

#define _USE_MATH_DEFINES
#include <iostream>
#include <vector>
#include <boost/shared_ptr.hpp>
//#include "Sublattice.h"
#include "Cell.h"


//! Neighbor class
/*!

*/
class Neighbors
{
public:
    //! Finds neighbors of two sublattices between distances min and max.
    //! Used exclusively by NeighborIter
    //! \param cell_in pointer to unit cell
    //! \param sublattice1_in pointer to first sublattice
    //! \param sublattice2_in pointer to second sublattice
    //! \param min minimum distance considered (Angstroms)
    //! \param max maximum distance considered (Angstroms)
    // returns relative position of all neighboring atoms
    Neighbors(boost::shared_ptr<Cell>& cell_in, boost::shared_ptr<Sublattice>& sublattice1_in, boost::shared_ptr<Sublattice>& sublattice2_in, double min, double max);
    AtomIterator begin();
    AtomIterator end();
private:
    std::vector<std::vector<double> >* neighbor_list;    //!< Stores list of neighbors generated by get_neighbors
};
#endif // __Neighbors_H__ 
